backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
# Beta feature - i18n Support
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Product"
    name: "products"
    folder: "src/equipment/products"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: duplicate
      - label: "Description"
        name: "description"
        required: false
        widget: "string"
        i18n: true
      - label: "Product Type"
        name: "productType"
        widget: "relation"
        collection: "productTypes"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "{{slug}}"
        i18n: duplicate
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        choose_url: false
        i18n: duplicate
      - label: Specifications
        name: "specs"
        widget: list
        collapsed: false
        i18n: true
        fields:
          - { label: "Label", name: "label", widget: "string", i18n: true }
          - { label: "Value", name: "value", widget: "string", i18n: duplicate }
        default:
          - { label: "Voltage", value: "220 V, 1-phase" }
          - { label: "Power", value: "kW" }
          - { label: "Dimension", value: "mm" }
          - { label: "Net weight", value: Kg" }
  - label: "Product Type"
    name: "productTypes"
    folder: "src/equipment/productTypes/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "markdown"
        i18n: true
      - label: "Product Category"
        name: "tags"
        widget: "relation"
        collection: "tags"
        search_fields: ["title"]
        display_fields: ["title"]
        value_field: "{{slug}}"
        multiple: true
        i18n: duplicate
  - label: "Product Category"
    name: "tags"
    folder: "src/equipment/productCategory/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    i18n: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        choose_url: false
        i18n: duplicate