backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/static/images"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Product"
    name: "products"
    folder: "src/equipment/products/"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "en"}
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        required: false
        widget: "string"
      - label: "Product Type"
        name: "productTypes"
        widget: "relation"
        collection: "productTypes"
        search_fields: ["title"]
        display_fields: ["{{title}}"]
        value_field: "title"
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        choose_url: false
      - label: Specifications
        name: "specs"
        widget: list
        collapsed: false
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "Value", name: "value", widget: "string" }
        default:
          - { label: "Voltage", value: "220 V, 1-phase" }
          - { label: "Power", value: "kW" }
          - { label: "Dimension", value: "mm" }
          - { label: "Net weight", value: Kg" }
  - label: "Product Type"
    name: "productTypes"
    folder: "src/equipment/productTypes/"
    create: true
    slug: "{{slug}}"
    filter: {field: "language", value: "en"}
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "markdown"
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options:
          - { label: "Packaging", value: "packaging" }
          - { label: "Baking", value: "baking" }
          - { label: "Stainless Steel Furniture", value: "ss-furniture" }